name: introduction_screen
description: Introduction/Onboarding package for flutter app with some customizations possibilities
version: 3.1.12
homepage: https://github.com/pyozer/introduction_screen

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  dots_indicator: ^2.1.2
  # flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
